# Generated by Django 2.1.8 on 2019-05-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=30)),
                ('continent_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Continent_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('country', models.CharField(max_length=30)),
                ('hashtag1', models.CharField(default='좋아용', max_length=10)),
                ('hashtag2', models.CharField(default='좋아용', max_length=10)),
                ('hashtag3', models.CharField(default='좋아용', max_length=10)),
                ('start_at', models.DateTimeField()),
                ('comeback_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
