# Generated by Django 2.1.8 on 2019-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190601_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='continent_blog',
            name='hashtag1',
        ),
        migrations.RemoveField(
            model_name='continent_blog',
            name='hashtag2',
        ),
        migrations.RemoveField(
            model_name='continent_blog',
            name='hashtag3',
        ),
        migrations.AddField(
            model_name='continent_blog',
            name='continent',
            field=models.CharField(default='gg', max_length=30),
        ),
        migrations.AddField(
            model_name='continent_blog',
            name='hashtag',
            field=models.CharField(default='gg', max_length=10),
        ),
    ]
