# Generated by Django 2.1.8 on 2019-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_continent_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent_blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='continent_blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
