# Generated by Django 2.1.8 on 2019-06-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190605_2040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent_blog',
            options={'ordering': ['-id']},
        ),
    ]
