# Generated by Django 2.1.8 on 2019-05-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20190527_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
